"""add food role

Revision ID: 33576a7db839
Revises: cda45893c49a
Create Date: 2026-08-08 23:57:35.865886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33576a7db839'
down_revision: Union[str, None] = 'cda45893c49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'foods',
        sa.Column(
            'role',
            sa.String(length=30),
            nullable=True
        )
    )

    op.execute(
        "UPDATE foods SET role = 'main' WHERE role IS NULL"
    )

    op.alter_column(
        'foods',
        'role',
        existing_type=sa.String(length=30),
        nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'role')
    # ### end Alembic commands ###
