"""add workout module tables

Revision ID: 439fb1e166cc
Revises: 83a1b3a745ac
Create Date: 2026-08-15 15:19:52.959241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439fb1e166cc'
down_revision: Union[str, None] = '83a1b3a745ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('force', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'expert', name='workout_level'), nullable=False),
    sa.Column('mechanic', sa.Enum('compound', 'isolation', name='workout_mechanic'), nullable=True),
    sa.Column('equipment', sa.Enum('body only', 'dumbbell', 'bands', 'machine', 'barbell', 'kettlebells', 'cable', 'foam roll', 'exercise ball', 'medicine ball', 'e-z curl bar', 'other', name='workout_equipment'), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('primary_muscles', sa.JSON(), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_equipment'), 'exercises', ['equipment'], unique=False)
    op.create_index(op.f('ix_exercises_level'), 'exercises', ['level'], unique=False)
    op.create_index(op.f('ix_exercises_mechanic'), 'exercises', ['mechanic'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('days_per_week', sa.Enum('1-2', '3-4', '5-6', name='workout_days_per_week'), nullable=False),
    sa.Column('goal', sa.Enum('strength', 'muscle_gain', 'fat_loss', name='workout_goal'), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'expert', name='workout_level'), nullable=False),
    sa.Column('equipment_available', sa.JSON(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='workout_gender'), nullable=False),
    sa.Column('focus_areas', sa.JSON(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('current_weight_kg', sa.Float(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workout_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('split_type', sa.Enum('full_body', 'upper_lower', 'ppl', name='workout_split_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['workout_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_muscle', sa.String(length=50), nullable=False),
    sa.Column('mechanic_preference', sa.Enum('compound', 'isolation', name='workout_mechanic'), nullable=True),
    sa.Column('chosen_exercise_id', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps_min', sa.Integer(), nullable=True),
    sa.Column('reps_max', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chosen_exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['day_id'], ['workout_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_slots')
    op.drop_table('workout_days')
    op.drop_table('workout_programs')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_mechanic'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_level'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
