"""add program expiry

Revision ID: a0e6bf05542a
Revises: 439fb1e166cc
Create Date: 2026-08-16 22:58:37.638287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e6bf05542a'
down_revision: Union[str, None] = '439fb1e166cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_programs', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_constraint('workout_slots_chosen_exercise_id_fkey', 'workout_slots', type_='foreignkey')
    op.create_foreign_key(None, 'workout_slots', 'exercises', ['chosen_exercise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_slots', type_='foreignkey')
    op.create_foreign_key('workout_slots_chosen_exercise_id_fkey', 'workout_slots', 'exercises', ['chosen_exercise_id'], ['id'])
    op.drop_column('workout_programs', 'expires_at')
    # ### end Alembic commands ###
